include:
  - project: "DevOps/templates"
    ref: "v2.0.4"
    file:
      - ".compile/js.yml"
      - ".build/npm.yml"
      - ".deploy/cloudfront.yml"

image: "node:21@sha256:4b232062fa976e3a966c49e9b6279efa56c8d207a67270868f51b3d155c4e33d"

variables:
  JIRA_PROJECT_NAME: "MINT"
  s3_bucket_production: "checkout-sdk.sezzle.com"
  s3_bucket_staging: "staging.checkout-sdk.sezzle.com"
  cf_dist_production: "E2HSGLI0811JNF"
  cf_dist_staging: "E2VP0QA9ZBJOEA"

deploy_cloudfront:afterpay_modals:
  extends:
    - .deploy_cloudfront
  environment: "afterpay_modals/${env_production}"
  tags:
    - ${tag_deploy_us}
  variables:
    S3_BUCKET: "sezzlemedia/afterpay"
    CF_DIST: "EFV0KW59BE883"
  script:
    - |
      log section "Copy static files to ./build"
      mkdir -p ./build/modal
      cp -v ./src/afterpay/modal/*.html ./build/modal
      log section-end
    - |
      aws_cloudfront_deploy --dryrun
      aws_cloudfront_deploy
  rules:
    - !reference [.deploy_default_rules]
    - !reference [.deploy_production_rules]
