include:
  - project: 'DevOps/templates'
    ref: 'v2.0.3'
    file:
      - '.compile/js.yml'
      - '.build/npm.yml'
      - '.deploy/cloudfront.yml'

image: 'node:20'

variables:
  JIRA_PROJECT_NAME: "MINT"
  s3_bucket_production: "checkout-sdk.sezzle.com"
  cf_dist_production: "EQ8554SMUE81E"

deploy_cloudfront:afterpay_modals:
  extends:
    - .deploy_cloudfront
  environment: "afterpay_modals/${env_production}"
  tags:
    - ${tag_deploy_us}
  variables:
    S3_BUCKET: "sezzlemedia/afterpay"
    CF_DIST: "EFV0KW59BE883"
  script:
    - |
      log section "Copy static files to ./build"
      mkdir -p ./build/modal
      cp -v ./src/afterpay/modal/*.html ./build/modal
      log section-end
    - |  
      aws_cloudfront_deploy --dryrun
      aws_cloudfront_deploy
  rules:
    - !reference [.deploy_default_rules]
    - !reference [.deploy_production_rules]
