include:
  - project: 'DevOps/templates'
    ref: 'v2.0.3'
    file:
      - '.compile/js.yml'
      - '.build/npm.yml'
      - '.deploy/cloudfront.yml'
      - '.compile/default.yml'

image: 'node:20'

variables:
  JIRA_PROJECT_NAME: "MINT"

deploy_cloudfront:checkout_button:
  tags:
    - ${tag_deploy_us}
  variables:
    s3_bucket_production: "checkout-sdk.sezzle.com"
    cf_dist_production: "EQ8554SMUE81E"

.before_script: |
  mkdir -p ./build
  cp -v ./src/afterpay/modal-en.html ./build/
  cp -v ./src/afterpay/modal-fr.html ./build/
  cp -v ./src/afterpay/modal-es.html ./build/

deploy_cloudfront:afterpay_modals:
  environment: "${env_production}"
  extends:
    - .deploy_cloudfront
  tags:
    - ${tag_deploy_us}
  variables:
    S3_BUCKET: "sezzlemedia/afterpay"
    CF_DIST: "EFV0KW59BE883"
  rules:
    - !reference [.deploy_default_rules]
    - !reference [.deploy_production_rules]
